---
root: true
plugins:
  - notice
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    legacyDecorators: true
env:
  node: true
  mocha: true
  browser: true
  es6: true
rules:
  camelcase: off
  curly:
    - error
    - all
  eqeqeq:
    - error
    - allow-null
  strict: off
  new-cap: error
  no-bitwise: error
  no-caller: error
  no-case-declarations: off
  no-cond-assign:
    - error
    - except-parens
  no-debugger: error
  no-empty: error
  no-eval: error
  no-extend-native: error
  no-irregular-whitespace: error
  no-iterator: error
  no-loop-func: error
  no-multi-str: error
  no-new: error
  no-proto: error
  no-script-url: error
  no-sequences: error
  no-undef: error
  no-with: error
  valid-typeof: error
  wrap-iife:
    - error
    - inside

  arrow-spacing: error
  prefer-const: error
  prefer-spread: error
  rest-spread-spacing: error
  template-curly-spacing: error

  notice/notice:
    - error
    - mustMatch: "(// Copyright \\d{4} [a-zA-Z0-9,\\.\\s]+\\n)+//\\n// Licensed under the Apache License, Version 2\\.0 \\(the \"License\"\\);\\n// you may not use this file except in compliance with the License\\.\\n// You may obtain a copy of the License at\\n//\\n//\\s+http://www\\.apache\\.org/licenses/LICENSE-2\\.0\\n//\\n// Unless required by applicable law or agreed to in writing, software\\n// distributed under the License is distributed on an \"AS IS\" BASIS,\\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\\n// See the License for the specific language governing permissions and\\n// limitations under the License\\.\\n"
